name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - run: touch ./src/main/resources/application-API-KEY.properties
      - run: echo "${{ secrets.EXTERNAL_KEY }}" > ./src/main/resources/application-API-KEY.properties
      - run: cat ./src/main/resources/application-API-KEY.properties

      - run: touch ./src/main/resources/application-uri.properties
      - run: echo "${{ secrets.EXTERNAL_URL }}" > ./src/main/resources/application-uri.properties
      - run: cat ./src/main/resources/application-uri.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
